AllCops:
  TargetRubyVersion: 2.3
Layout/DotPosition:
  EnforcedStyle: trailing
Metrics/BlockLength:
  Exclude:
    - '*.gemspec'
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'
Metrics/LineLength:
  Enabled: False
Naming/FileName:
  Exclude:
    - 'lib/help_scout-sdk.rb'
Style/Documentation:
  Enabled: False
