AllCops:
  TargetRubyVersion: 2.3

Layout/DotPosition:
  EnforcedStyle: trailing

Lint/AmbiguousBlockAssociation:
  Exclude:
    - 'spec/**/*_spec.rb'

Metrics/BlockLength:
  Exclude:
    - 'helpscout.gemspec'
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*_spec.rb'

Metrics/ClassLength:
  Max: 125

Metrics/LineLength:
  Max: 120

Style/Documentation:
  Enabled: False
