AllCops:
  TargetRubyVersion: 2.3
Metrics/BlockLength:
  Exclude:
    - 'help_scout_sdk.gemspec'
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'
Layout/DotPosition:
  EnforcedStyle: trailing
Metrics/LineLength:
  Enabled: False
Style/Documentation:
  Enabled: False
